content:
  application/json:
    schema:
      $ref: ../schemas/ProductFlagsResponse.yaml
description: Fortress Flags Response
headers:
  x-ratelimit-limit:
    $ref: ../headers/XRateLimitHeader.yaml
  x-ratelimit-remaining:
    $ref: ../headers/XRateLimitRemainingHeader.yaml
