content:
  application/json:
    schema:
      $ref: ../schemas/UserSettingsResponse.yaml
description: User Settings Response
headers:
  x-ratelimit-limit:
    $ref: ../headers/XRateLimitHeader.yaml
  x-ratelimit-remaining:
    $ref: ../headers/XRateLimitRemainingHeader.yaml
