get:
  tags:
    - Organizations
  operationId: getOrganizationSettings
  summary: Get organization settings and admin panel permissions
  responses:
    '200':
      $ref: ../components/responses/GetOrganizationSettings200.yaml
