name: Build & Release OpenAPI Bundles

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  bundle-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@1.34.3

      - name: Bundle OpenAPI specs
        run: |
          redocly bundle openapi@v4 --output openapi.v4.yaml
          redocly bundle openapi@v5 --output openapi.v5.yaml

      - name: Copy specs to docs/ for GitHub Pages
        run: |
          mkdir -p docs
          cp openapi.v4.yaml docs/openapi.v4.yaml
          cp openapi.v5.yaml docs/openapi.v5.yaml

      - name: Commit and push updated docs/ (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/openapi.v*.yaml
          git diff --cached --quiet || git commit -m "Update bundled OpenAPI specs in docs/"
          git push origin HEAD:main

      - name: Create GitHub Release from tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: |
            openapi.v4.yaml
            openapi.v5.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
