name: Sync swagger.yaml to docs/

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compare swagger.yaml to docs/
        id: compare
        run: |
          mkdir -p docs
          if ! cmp -s swagger.yaml docs/swagger.yaml; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Sync and commit if changed
        if: steps.compare.outputs.changed == 'true'
        run: |
          cp swagger.yaml docs/swagger.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/swagger.yaml
          git commit -m "Sync swagger.yaml to docs/"
          git push
